[build]
packages = ["pkg-config", "mariadb-connector-c"]

[build.env]
MYSQLCLIENT_CFLAGS = "-I/usr/include/mariadb"
MYSQLCLIENT_LDFLAGS = "-L/usr/lib/x86_64-linux-gnu -lmariadb"

# Agregamos un paso para imprimir las variables antes de continuar
command = "echo MYSQLCLIENT_CFLAGS=$MYSQLCLIENT_CFLAGS && echo MYSQLCLIENT_LDFLAGS=$MYSQLCLIENT_LDFLAGS && python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"
