[build]
packages = ["pkg-config", "mariadb-connector-c"]
# Se sobreescribe el comando de build para exportar los flags de mysqlclient
command = "export MYSQLCLIENT_CFLAGS=$(pkg-config --cflags mariadb-connector-c) && export MYSQLCLIENT_LDFLAGS=$(pkg-config --libs mariadb-connector-c) && python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"
