[build]
packages = ["pkg-config", "mariadb-connector-c"]
command = "export MYSQLCLIENT_CFLAGS='-I/usr/include/mariadb' && export MYSQLCLIENT_LDFLAGS='-L/usr/lib/x86_64-linux-gnu -lmariadb' && python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"
