[build]
# No es necesario instalar paquetes específicos para MySQL, solo las dependencias básicas
packages = [
    "gcc",
    "python3-dev",
    "libssl-dev"
]

command = "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install --no-cache-dir -r requirements.txt"
