# nixpacks.toml
[build]
packages = [
    "pkg-config",
    "libmariadb-dev-compat",  # Paquete clave para Debian/Ubuntu
    "gcc",
    "python3-dev"
]

[build.environment]
MYSQLCLIENT_CFLAGS = "-I/usr/include/mariadb"
MYSQLCLIENT_LDFLAGS = "-L/usr/lib/x86_64-linux-gnu -lmariadb"