[build]
packages = ["pkg-config", "mariadb-connector-c"]

[build.env]
MYSQLCLIENT_CFLAGS = "-I/usr/include/mariadb"
MYSQLCLIENT_LDFLAGS = "-L/usr/lib/x86_64-linux-gnu -lmariadb"
PKG_CONFIG_PATH = "/usr/lib/x86_64-linux-gnu/pkgconfig"

command = "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"
