# Generated by Django 5.0.6 on 2025-12-03 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, null=True)),
                ('diagnostico_principal', models.TextField(blank=True)),
                ('procedimiento_propuesto', models.TextField(blank=True)),
                ('beneficios', models.TextField(blank=True)),
                ('riesgos', models.TextField(blank=True)),
                ('alternativas', models.TextField(blank=True)),
                ('testigo1_nombre', models.CharField(blank=True, max_length=255)),
                ('testigo2_nombre', models.CharField(blank=True, max_length=255)),
                ('lugar', models.CharField(default='Zihuatanejo, Guerrero', max_length=255)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('firma_paciente', models.ImageField(blank=True, null=True, upload_to='users/firmas/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcedimientoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', help_text='Estado del pago específico de este procedimiento.', max_length=20)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, null=True)),
                ('indicaciones_generales', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='RecetaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('dosis', models.CharField(blank=True, max_length=255)),
                ('frecuencia', models.CharField(blank=True, max_length=255)),
                ('duracion', models.CharField(blank=True, max_length=255)),
                ('via_administracion', models.CharField(blank=True, max_length=255)),
                ('notas', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportePaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, null=True)),
                ('resumen', models.TextField()),
                ('diagnostico', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('FINAL', 'Final')], default='FINAL', max_length=10)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='atendida',
            field=models.BooleanField(default=False, help_text='Indica si la cita ya fue atendida (consulta y receta completas).'),
        ),
        migrations.AddField(
            model_name='cita',
            name='consentimiento_completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cita',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='metodo_pago_preferido',
            field=models.CharField(blank=True, choices=[('TRANSFERENCIA', 'Transferencia / Depósito'), ('CONSULTORIO', 'Pago en consultorio')], help_text='Método de pago preferido (informativo) para esta cita.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='requiere_consentimiento',
            field=models.BooleanField(default=False, help_text='Indica si las citas de esta especialidad requieren consentimiento informado.'),
        ),
        migrations.AddField(
            model_name='pago',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_reverso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('TRANSFERENCIA', 'Transferencia / Depósito'), ('CONSULTORIO', 'Pago en consultorio')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='motivo_reverso',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='revertido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='motivo_cierre',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_tratamiento', to='users.tratamiento'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='users/comprobantes/'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['DERMATOLOGO', 'PODOLOGO', 'TAMIZ']}, on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='paciente',
            field=models.ForeignKey(limit_choices_to={'role': 'PACIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos_paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='tratamiento',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('paciente', 'doctor'), name='unique_active_tratamiento_paciente_doctor'),
        ),
        migrations.AddField(
            model_name='consentimiento',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consentimiento',
            name='cita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consentimiento', to='users.cita'),
        ),
        migrations.AddField(
            model_name='consentimiento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimientoconsulta',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimientoconsulta',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='users.cita'),
        ),
        migrations.AddField(
            model_name='procedimientoconsulta',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimientoconsulta',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['DERMATOLOGO', 'PODOLOGO', 'TAMIZ']}, on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimientoconsulta',
            name='paciente',
            field=models.ForeignKey(limit_choices_to={'role': 'PACIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos_paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receta',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receta',
            name='cita',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receta', to='users.cita'),
        ),
        migrations.AddField(
            model_name='receta',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receta',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['DERMATOLOGO', 'PODOLOGO', 'TAMIZ']}, on_delete=django.db.models.deletion.CASCADE, related_name='recetas_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receta',
            name='paciente',
            field=models.ForeignKey(limit_choices_to={'role': 'PACIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='recetas_paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recetamedicamento',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='users.receta'),
        ),
        migrations.AddField(
            model_name='reportepaciente',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportepaciente',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='users.cita'),
        ),
        migrations.AddField(
            model_name='reportepaciente',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportepaciente',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['DERMATOLOGO', 'PODOLOGO', 'TAMIZ']}, on_delete=django.db.models.deletion.CASCADE, related_name='reportes_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportepaciente',
            name='paciente',
            field=models.ForeignKey(limit_choices_to={'role': 'PACIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='reportes_paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='procedimientoconsulta',
            index=models.Index(fields=['cita'], name='users_proce_cita_id_235ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='procedimientoconsulta',
            index=models.Index(fields=['paciente'], name='users_proce_pacient_7920e6_idx'),
        ),
        migrations.AddIndex(
            model_name='procedimientoconsulta',
            index=models.Index(fields=['doctor'], name='users_proce_doctor__c47127_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportepaciente',
            constraint=models.UniqueConstraint(condition=models.Q(('cita__isnull', False)), fields=('cita',), name='unique_reporte_por_cita_no_nula'),
        ),
    ]
